[BUGFIX] Add required typo3/cms-reports
This fixes lots of CI errors:

    Error: Interface "TYPO3\CMS\Reports\StatusProviderInterface" not found

Signed-off-by: Stefan Weil <sw@weilnetz.de>